## Not being used
server:
  extraArgs:
    - --insecure
  
  service:
    type: ClusterIP
  
  ingress:
    enabled: true
    ingressClassName: "traefik"

    annotations:
      traefik.ingress.kubernetes.io/redirect-entry-point: "web"

    hosts:
      - argocd.127.0.0.1.nip.io

