apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-http
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`whoami.127.0.0.1.nip.io`)
    kind: Rule
    services:
    - name: whoami
      port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-https
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`whoami.127.0.0.1.nip.io`)
    kind: Rule
    services:
    - name: whoami
      port: 80
  tls:
    secretName: cert-whoami
    domains:
    - main: whoami.127.0.0.1.nip.io

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-http
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`traefik.127.0.0.1.nip.io`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-https
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`traefik.127.0.0.1.nip.io`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
  tls:
    secretName: cert-traefik
    domains:
    - main: traefik.127.0.0.1.nip.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
spec:
  dnsNames:
  - whoami.127.0.0.1.nip.io
  - traefik.127.0.0.1.nip.io
  secretName: cert-whoami
  issuerRef:
    name: self-signed
    kind: ClusterIssuer

---
## cert for Traefik
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
spec:
  dnsNames:
  - traefik.127.0.0.1.nip.io
  secretName: cert-traefik
  issuerRef:
    name: self-signed
    kind: ClusterIssuer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingress
  namespace: monitoring
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`prometheus.127.0.0.1.nip.io`)
    kind: Rule
    services:
    - name: prometheus-server
      port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: monitoring
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`grafana.127.0.0.1.nip.io`)
    kind: Rule
    services:
    - name: grafana
      port: 80
