apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-http
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`whoami.127.0.0.1.nip.io`)
    kind: Rule
    services:
    - name: whoami
      port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-https
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`whoami.127.0.0.1.nip.io`)
    kind: Rule
    services:
    - name: whoami
      port: 80
  tls:
    secretName: cert-whoami
    domains:
    - main: whoami.127.0.0.1.nip.io

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`traefik.127.0.0.1.nip.io`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
spec:
  dnsNames:
  - whoami.127.0.0.1.nip.io
  secretName: cert-whoami
  issuerRef:
    name: self-signed
    kind: ClusterIssuer
